#!/bin/sh

for OPT in "$@"
do
    case $OPT in
        --config)
            rm -r config
            rm -f build.log
            exit 0
            ;;
    esac
done            

lb clean noauto "${@}"
